# Practice Questions Set 1

#### 1.How to create an empty and a full NumPy array?

In [ ]:
import numpy as np
  
  
#Create an empty array
empa = np.empty((3, 4), dtype=int)
print("Empty Array")
print(empa)
  
# Create a full array
flla = np.full([3, 3], 55, dtype=int)
print("\n Full Array")
print(flla)

Empty Array
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

 Full Array
[[55 55 55]
 [55 55 55]
 [55 55 55]]


#### 2.Create a Numpy array filled with all zeros | Python

In [ ]:
import numpy as np 
  
a = np.zeros(3, dtype = int) 
print("Matrix a : \n", a) 
  
b = np.zeros([3, 3], dtype = int) 
print("\nMatrix b : \n", b) 

Matrix a : 
 [0 0 0]

Matrix b : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


#### 3.Create a Numpy array filled with all ones

In [ ]:
import numpy as np
  
a = np.ones(3, dtype = int) 
print("Matrix a : \n", a) 
  
b = np.ones([3, 3], dtype = int) 
print("\nMatrix b : \n", b) 

Matrix a : 
 [1 1 1]

Matrix b : 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


#### 4.Check whether a Numpy array contains a specified row

In [ ]:
import numpy
  
# create numpy array
arr = numpy.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])
  
# view array
print(arr)
  
# check for some lists
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
True


#### 5.Code to Remove rows in Numpy array that contains non-numeric values?

In [ ]:
import numpy as np
  
# Creating 5X4 2-D Numpy array
n_arr = np.array([[10.5, 22.5, 3.8, 5],
                  [23.45, 50, 78.7, 3.5],
                  [41, np.nan, np.nan, 0],
                  [20, 50.20, np.nan, 2.5],
                  [18.8, 50.60, 8.8, 58.6]])
  
print("Given array:")
print(n_arr)
  
print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])

Given array:
[[10.5  22.5   3.8   5.  ]
 [23.45 50.   78.7   3.5 ]
 [41.     nan   nan  0.  ]
 [20.   50.2    nan  2.5 ]
 [18.8  50.6   8.8  58.6 ]]

Remove all rows containing non-numeric elements
[[10.5  22.5   3.8   5.  ]
 [23.45 50.   78.7   3.5 ]
 [18.8  50.6   8.8  58.6 ]]


#### 6.Find the number of occurrences of a sequence in a NumPy array

In [ ]:
import numpy
  
# create numpy array
arr = numpy.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
  
# Counting sequence
output = repr(arr).count("9, 4")
  
# view output
print(output) 

4


#### 7.Removing single-dimensional entries from the shape of array
* numpy.squeeze() function is used when we want to remove single-dimensional entries from the shape of an array.

In [ ]:
import numpy as geek
  
in_arr = geek.array([[[2, 2, 2], [2, 2, 2]]])
   
print ("Input array : ", in_arr) 
print("Shape of input array : ", in_arr.shape)  
  
out_arr = geek.squeeze(in_arr) 
  
print ("output squeezed array : ", out_arr)
print("Shape of output array : ", out_arr.shape) 

Input array :  [[[2 2 2]
  [2 2 2]]]
Shape of input array :  (1, 2, 3)
output squeezed array :  [[2 2 2]
 [2 2 2]]
Shape of output array :  (2, 3)


#### 8.Find the most frequent value in a NumPy array

In [ ]:
import numpy as np
  
  
# create array
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(x)
  
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


#### 9.Combining a one and a two-dimensional NumPy Array

In [ ]:
import numpy as np
  
num_1d = np.arange(5)
print("One dimensional array:")
print(num_1d)
  
num_2d = np.arange(10).reshape(2,5)
print("\nTwo dimensional array:")
print(num_2d)
  
# Combine 1-D and 2-D arrays and display 
# their elements using numpy.nditer() 
for a, b in np.nditer([num_1d, num_2d]):
    print("%d:%d" % (a, b),)

One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


#### 10.How to build an array of all combinations of two NumPy arrays?
* Numpy meshgride():This function is used to create a rectangular grid out of two given one-dimensional arrays representing the Cartesian indexing or Matrix indexing

In [ ]:
import numpy as np
  
# creating 2 numpy arrays
array_1 = np.array([1, 2])
array_2 = np.array([4, 6])
  
print("Array-1")
print(array_1)
  
print("\nArray-2")
print(array_2)
  
# combination of elements of array_1 and array_2
# using numpy.meshgrid().T.reshape()
comb_array = np.array(np.meshgrid(array_1, array_2)).T.reshape(-1, 2)
  
print("\nCombine array:")
print(comb_array)

Array-1
[1 2]

Array-2
[4 6]

Combine array:
[[1 4]
 [1 6]
 [2 4]
 [2 6]]


#### 11.How to add a border around a NumPy array?
* Numpy provides a function known as ‘numpy.pad()’ to construct the border. 

In [ ]:
import numpy as np
  
# Creating a 2X2 Numpy matrix
array = np.ones((2, 2))
  
print("Original array")
print(array)
  
print("\n0 on the border and 1 inside the array")
  
# constructing border of 0 around 2D identity matrix
# using np.pad()
array = np.pad(array, pad_width=1, mode='constant',
               constant_values=0)
  
print(array)

Original array
[[1. 1.]
 [1. 1.]]

0 on the border and 1 inside the array
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


#### 12.How to compare two NumPy arrays?

In [ ]:
import numpy as np
  
  
a = np.array([101, 99, 87])
b = np.array([897, 97, 111])
  
print("Array a: ", a)
print("Array b: ", b)
  
print("a > b")
print(np.greater(a, b))
  
print("a >= b")
print(np.greater_equal(a, b))
  
print("a < b")
print(np.less(a, b))
  
print("a <= b")
print(np.less_equal(a, b))

Array a:  [101  99  87]
Array b:  [897  97 111]
a > b
[False  True False]
a >= b
[False  True False]
a < b
[ True False  True]
a <= b
[ True False  True]


#### 13.How to check whether specified values are present in NumPy array?

In [ ]:
import numpy as np
  
# creating a Numpy array
n_array = np.array([[2, 3, 0],
                    [4, 1, 6]])
  
print("Given array:")
print(n_array)
  
# Checking whether specific values
# are present in "n_array" or not
print(2 in n_array)
print(0 in n_array)
print(6 in n_array)
print(50 in n_array)
print(10 in n_array)

Given array:
[[2 3 0]
 [4 1 6]]
True
True
True
False
False


#### 14.How to get all 2D diagonals of a 3D NumPy array?
* Numpy.diagonal()::-->This function return specified diagonals from an n-dimensional array. 



In [ ]:
import numpy as np
  
# Create 3D-numpy array
# of 4 rows and 4 columns
arr = np.arange(3 * 4 * 4).reshape(3, 4, 4)
  
print("Original 3d array:\n", 
      arr)
  
# Create 2D diagonal array
diag_arr = np.diagonal(arr, 
                       axis1 = 1,
                       axis2 = 2)
  
print("2d diagonal array:\n", 
      diag_arr)

Original 3d array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
2d diagonal array:
 [[ 0  5 10 15]
 [16 21 26 31]
 [32 37 42 47]]


#### 15.Change data type of given numpy array

In [ ]:
import numpy as np
  
# Create a numpy array
arr = np.array([10, 20, 30, 40, 50])
  
# Print the array
print(arr)

print(arr.dtype)

arr = arr.astype('float64')
  
# Print the array after changing
# the data type
print(arr)
  
# Also print the data type
print(arr.dtype)

[10 20 30 40 50]
int64
[10. 20. 30. 40. 50.]
float64


#### 16.Reverse a numpy array

In [ ]:
import numpy as np
  
# initialising numpy array
ini_array = np.array([1, 2, 3, 6, 4, 5])
  
# printing initial ini_array
print("initial array", str(ini_array))
  
# printing type of ini_array
print("type of ini_array", type(ini_array))
  
# using shortcut method to reverse
res = ini_array[::-1]
  
# printing result
print("final array", str(res))

initial array [1 2 3 6 4 5]
type of ini_array <class 'numpy.ndarray'>
final array [5 4 6 3 2 1]


#### 17.Find the sum of values in  a array

In [ ]:
import numpy as np
             
# make matrix with numpy
tr = np.matrix('[4, 1; 12, 3]')
             
# applying matrix.sum() method
g = tr.sum()
   
print(g)

20


#### 18.Replace NumPy array elements that doesn’t satisfy the given condition

In [ ]:
import numpy as np
  
# Creating a 1-D Numpy array
n_arr = np.array([75.42436315, 42.48558583, 60.32924763])
print("Given array:")
print(n_arr)
  
print("\nReplace all elements of array which are greater than 50. to 15.50")
n_arr[n_arr > 50.] = 15.50
  
print("New array :\n")
print(n_arr)

Given array:
[75.424 42.486 60.329]

Replace all elements of array which are greater than 50. to 15.50
New array :

[15.5   42.486 15.5  ]


#### 19.Return the indices of element where the given condition is satisfied

In [ ]:
import numpy as np
  
# a is an array of integers.
a = np.array([[1, 2, 3], [4, 5, 6]])
  
print(a)
  
print ('Indices of elements <4')
  
b = np.where(a<4)
print(b)
  
print("Elements which are <4")
print(a[b])

[[1 2 3]
 [4 5 6]]
Indices of elements <4
(array([0, 0, 0]), array([0, 1, 2]))
Elements which are <4
[1 2 3]


#### 20.Replace NaN values with average of columns

In [ ]:
import numpy as np
  
# Initialising numpy array
ini_array = np.array([[1.3, 2.5, 3.6, np.nan], 
                      [2.6, 3.3, np.nan, 5.5],
                      [2.1, 3.2, 5.4, 6.5]])
  
# printing initial array
print ("initial array", ini_array)
  
# column mean
col_mean = np.nanmean(ini_array, axis = 0)
  
# printing column mean
print ("columns mean", str(col_mean))
  
# find indices where nan value is present
inds = np.where(np.isnan(ini_array))
  
# replace inds with avg of column
ini_array[inds] = np.take(col_mean, inds[1])
  
# printing final array
print ("final array", ini_array)

initial array [[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]
columns mean [2.  3.  4.5 6. ]
final array [[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


#### 21.Replace negative value with zero in numpy array

In [ ]:
import numpy as np
  
ini_array1 = np.array([1, 2, -3, 4, -5, -6])
  
# printing initial arrays
print("initial array", ini_array1)
  
# code to replace all negative value with 0
ini_array1[ini_array1<0] = 0
  
# printing result
print("New resulting array: ", ini_array1)

initial array [ 1  2 -3  4 -5 -6]
New resulting array:  [1 2 0 4 0 0]


#### 22.How to get values of an NumPy array at certain index positions?

In [ ]:
import numpy as np
  
# Creating 1-D Numpy array
a1 = np.array([11, 10, 22, 30, 33])
print("Array 1 :")
print(a1)
  
a2 = np.array([1, 15, 60])
print("Array 2 :")
print(a2)
  
print("\nTake 1 and 15 from Array 2 and put them in\
1st and 5th position of Array 1")
  
a1.put([0, 4], a2)
  
print("Resultant Array :")
print(a1)

Array 1 :
[11 10 22 30 33]
Array 2 :
[ 1 15 60]

Take 1 and 15 from Array 2 and put them in1st and 5th position of Array 1
Resultant Array :
[ 1 10 22 30 15]


#### 23.Find indices of elements equal to zero in a NumPy array

In [ ]:
import numpy as np
  
# creating a 1-D Numpy array
n_array = np.array([1, 0, 2, 0, 3, 0, 0, 5,
                    6, 7, 5, 0, 8])
  
print("Original array:")
print(n_array)
  
# finding indices of null elements using np.where()
print("\nIndices of elements equal to zero of the \
given 1-D array:")
  
res = np.where(n_array == 0)[0]
print(res)

Original array:
[1 0 2 0 3 0 0 5 6 7 5 0 8]

Indices of elements equal to zero of the given 1-D array:
[ 1  3  5  6 11]


#### 24.Get row numbers of NumPy array having element larger than X

In [ ]:
import numpy
  
# create numpy array
arr = numpy.array([[1, 2, 3, 4, 5],
                  [10, -3, 30, 4, 5],
                  [3, 2, 5, -4, 5],
                  [9, 7, 3, 6, 5] 
                 ])
  
# declare specified value
X = 6
  
# view array
print("Given Array:\n", arr)
  
# finding out the row numbers
output  = numpy.where(numpy.any(arr > X,
                                axis = 1))
  
# view output
print("Result:\n", output)

Given Array:
 [[ 1  2  3  4  5]
 [10 -3 30  4  5]
 [ 3  2  5 -4  5]
 [ 9  7  3  6  5]]
Result:
 (array([1, 3]),)


#### 25.fill daigonal value with x

In [ ]:
import numpy as np
x=5  
# using numpy.fill_diagonal() method
array = np.array([[1, 2], [2, 1]])
np.fill_diagonal(array, x)
  
print(array)

[[5 2]
 [2 5]]


#### 26.Check element present in array or not 
* With the help of numpy.isin() method

In [ ]:
import numpy as np
  
# using numpy.isin() method
g1 = np.array([1, 2, 3, 4, 5])
lis = [1, 3, 5]
g = np.isin(g1, lis)
  
print(g)

[ True False  True False  True]


#### 27.Create a Numpy array with random values | Python

In [ ]:
import numpy as np 
    
b = np.empty(2, dtype = int) 
print("Matrix b : \n", b) 
    
a = np.empty([2, 2], dtype = int) 
print("\nMatrix a : \n", a) 

Matrix b : 
 [3 2]

Matrix a : 
 [[4611686018427387904 4613937818241073152]
 [4616752568008179712 4618441417868443648]]


#### 28.How to choose elements from the list with different probability using NumPy?

In [ ]:
import numpy as np
  
# create a list
num_list = [10, 20, 30, 40, 50]
  
# uniformly select any element
# from the list
number = np.random.choice(num_list)
  
print(number)

50


#### 29.Create array with elements which follow normal distribution

In [ ]:
import numpy as np
a=np.random.randn(210,10,50)
print(a)

#### 30.Generate Random Numbers From The Uniform Distribution using NumPy

In [ ]:
import numpy as np
  
  
# numpy.random.uniform() method
r = np.random.uniform(size=4)
  
print(r)

[0.619 0.189 0.973 0.264]


#### 31.Repeat all the elements of a NumPy array of strings

In [ ]:
import numpy as np
  
# created array of strings
arr = np.array(['Akash', 'Rohit', 'Ayush', 
                'Dhruv', 'Radhika'], dtype = np.str)
print("Original Array :")
print(arr)
  
# with the help of np.char.multiply()
# repeating the characters 3 times
new_array = np.char.multiply(arr, 3)
print("\nNew array :")
print(new_array)

Original Array :
['Akash' 'Rohit' 'Ayush' 'Dhruv' 'Radhika']

New array :
['AkashAkashAkash' 'RohitRohitRohit' 'AyushAyushAyush' 'DhruvDhruvDhruv'
 'RadhikaRadhikaRadhika']


#### 32.How to create a 1D array?

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 33.How to create a boolean array?

In [ ]:
np.full((3, 3), True, dtype=bool)
#> array([[ True,  True,  True],
#>        [ True,  True,  True],
#>        [ True,  True,  True]], dtype=bool)

# Alternate method:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### 34.How to extract items that satisfy a given condition from 1D array?

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 == 1]
#> array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

#### 35.How to replace items that satisfy a condition with another value in numpy array?

In [ ]:
arr[arr % 2 == 1] = -1
arr
#> array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### 36.How to replace items that satisfy a condition without affecting the original array?

In [ ]:
import numpy as np
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out
#> [0 1 2 3 4 5 6 7 8 9]
np.array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### 37. How to reshape an array?

In [ ]:
arr = np.arange(10)
arr.reshape(2, 5)  # Setting to -1 automatically decides the number of cols
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### 38.How to stack two arrays vertically?

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

# Method 3:
np.r_[a, b]
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### 39.How to stack two arrays horizontally?

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

# Method 3:
np.c_[a, b]
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

#### 40.How to generate custom sequences in numpy without hardcoding?

In [ ]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

#### 41.How to get the common items between two python numpy arrays?

In [ ]:
 a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

#### 42.How to remove from one array those items that exist in another?

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)
#> array([1, 2, 3, 4])

array([1, 2, 3, 4])

#### 43.How to get the positions where elements of two arrays match?

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

##### 45.How to extract all numbers between a given range from a numpy array?

In [ ]:
a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),)

# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

#### 46.How to make a python function that handles scalars to work on numpy arrays?

In [ ]:
def maxx(x, y):
    print('Get the maximum of two items')
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5

Get the maximum of two items


5

#### 47.How to swap two columns in a 2d numpy array?

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)

# Solution
arr[:, [1,0,2]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

#### 48.How to swap two rows in a 2d numpy array?

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)

# Solution
arr[[1,0,2], :]
#> array([[3, 4, 5],
#>        [0, 1, 2],
#>        [6, 7, 8]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

##### 49. How to reverse the rows of a 2D array?

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)
# Solution
arr[::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

#### 50.How to reverse the columns of a 2D array?

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr)

# Solution
arr[:, ::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

#### 51.How to create a 2D array containing random floats between 5 and 10?

In [ ]:
arr = np.arange(9).reshape(3,3)

# Solution Method 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
# print(rand_arr)

# Solution Method 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[7.125 9.973 7.162]
 [7.204 5.177 6.536]
 [7.606 5.06  6.836]
 [7.423 8.784 9.945]
 [6.307 9.129 7.741]]


#### 52.How to print only 3 decimal places in python numpy array?

In [ ]:
rand_arr = np.random.random((5,3))

# Create the random array
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.157, 0.365, 0.736],
       [0.657, 0.359, 0.299],
       [0.311, 0.939, 0.082],
       [0.79 , 0.391, 0.488]])

#### 53.How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [ ]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

#### 54. How to compute the mean, median, standard deviation of a numpy array?

In [ ]:
x=np.random.randn(20,16,50)
x_mean=np.mean(x)
x_median=np.median(x)
x_std=np.std(x)
print(x_mean,x_median,x_std)

-0.0021003534273936757 0.0031421103948110346 0.9920645108442112


#### 55.Create a 4X2 integer array and Prints its attributes

In [ ]:
import numpy

firstArray = numpy.empty([4,2], dtype = numpy.uint16) 
print("Printing Array")
print(firstArray)

print("Printing numpy array Attributes")
print("1> Array Shape is: ", firstArray.shape)
print("2>. Array dimensions are ", firstArray.ndim)
print("3>. Length of each element of array in bytes is ", firstArray.itemsize)

Printing Array
[[5 0]
 [0 0]
 [3 0]
 [0 0]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


#### 56.Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [ ]:
import numpy

print("Creating 5X2 array using numpy.arange")
sampleArray = numpy.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


#### 57.Following is the provided numPy array. Return array of items by taking the third column from all rows
* sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

In [ ]:
import numpy

sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of items in the third column from all rows")
newArray = sampleArray[...,2]
print(newArray)

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[33 66 99]


#### 58.Return array of odd rows and even columns from below numpy arra

In [ ]:
import numpy

sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of odd rows and even columns")
newArray = sampleArray[::2, 1::2]
print(newArray)

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

 Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


#### 59.Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element

In [ ]:
import numpy

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

resultArray  = arrayOne + arrayTwo
print("addition of two arrays is \n")
print(resultArray)

for num in numpy.nditer(resultArray, op_flags = ['readwrite']):
   num[...] = num*num
print("\nResult array after calculating the square root of all elements\n")
print(resultArray)

addition of two arrays is 

[[20 39 33]
 [25 25 28]]

Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]


#### 60.Split the array into four equal-sized sub-arrays

In [ ]:
import numpy

print("Creating 8X3 array using numpy.arange")
sampleArray = numpy.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8,3)
print (sampleArray)

print("\nDividing 8X3 array into 4 sub array\n")
subArrays = numpy.split(sampleArray, 4) 
print(subArrays)

Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 ...
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


#### 61.Print max from axis 0 and min from axis 1 from the following 2-D array.

In [ ]:
import numpy

print("Printing Original array")
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

minOfAxisOne = numpy.amin(sampleArray, 1) 
print("Printing amin Of Axis 1")
print(minOfAxisOne)

maxOfAxisOne = numpy.amax(sampleArray, 0) 
print("Printing amax Of Axis 0")
print(maxOfAxisOne)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Printing amin Of Axis 1
[34 12 53]
Printing amax Of Axis 0
[82 94 73]


#### 62.Delete the second column from a given array and insert the following new column in its place.
* sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = numpy.array([[10,10,10]])`

In [ ]:
import numpy

print("Printing Original array")
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = numpy.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = numpy.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = numpy.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


#### 63.Element-wise addition of 2 numpy arrays

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

c = a + b

print(c)


[[11 13 15]
 [17 19 21]]


#### 64.Multiplying a matrix (numpy array) by a scalar

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

b = 2*a # multiplying the numpy array a(matrix) by 2

print(b)

[[ 2  4  6]
 [ 8 10 12]]


##### 65.Create Identity Matrix

In [ ]:
i = np.eye(4)

print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### 66.Create Boolean Array from Binary Array

In [ ]:
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])

o = a.astype('bool')

print(o)

[[ True False False]
 [ True  True  True]
 [False False False]]


#### 67.Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

In [ ]:
list_of_numbers = [x for x in range(0, 101, 2)]

o = np.array(list_of_numbers)

print(o)

[  0   2   4 ...  96  98 100]


#### 68.from 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

In [ ]:
a = np.array([1,2,3,4,5])

b = np.array([1,3,2,4,5])

print(np.where(a == b))

(array([0, 3, 4]),)


#### 69.Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive)

In [ ]:
 o = np.linspace(0, 100, 5)

print(o)
 

[  0.  25.  50.  75. 100.]


#### 70.Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5

In [ ]:
a = np.ones((2, 3))

o = 5*a

print(o)

[[5. 5. 5.]
 [5. 5. 5.]]


#### 71.Output an array by repeating a smaller array of 2 dimensions, 10 times

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

o = np.tile(a, 10)

print(o)

[[1 2 3 ... 1 2 3]
 [4 5 6 ... 4 5 6]]


#### 72.Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)

In [ ]:
 np.random.seed(123) # setting the seed

o = np.random.randint(0, 10, size = (5,5))

print(o)

[[2 2 6 1 3]
 [9 6 1 0 1]
 [9 0 0 9 3]
 [4 0 0 4 1]
 [7 3 2 4 7]]


#### 73.Output a 3-by-3 array of random numbers following normal distribution

In [ ]:
np.random.seed(123) # setting the seed

o = np.random.normal(size = (3,3))

print(o)

[[-1.086  0.997  0.283]
 [-1.506 -0.579  1.651]
 [-2.427 -0.429  1.266]]


#### 74.Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

o = a@b

print(o)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


#### 75.Output the transpose of a matrix (as numpy array

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

a_transpose = a.T

print(a_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### 76.Calculate the sine of an array of angles (in radians) using NumPy

In [ ]:
angles = np.array([3.14, 3.14/2, 6.28])

sine_of_angles = np.sin(angles)

print('Sine of the given array of angles = ', sine_of_angles)

Sine of the given array of angles =  [ 0.002  1.    -0.003]


#### 77.Calculate the cosine similarity of 2 vectors (as numpy arrays)

In [ ]:
angles = np.array([3.14, 3.14/2, 6.28])

cosine_of_angles = np.cos(angles)

print('Cosine of the given array of angles = ', cosine_of_angles)

Cosine of the given array of angles =  [-1.000e+00  7.963e-04  1.000e+00]


#### 78.Output the array element indexes such that the array elements appear in the ascending order

In [ ]:
array = np.array([10,1,5,2])

indexes = np.argsort(array)

print(indexes)
 

[1 3 2 0]


#### 79.Write a NumPy program to get the numpy version and show numpy build configuration.

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 80.Write a NumPy program to get help on the add function.

In [ ]:
import numpy as np
print(np.info(np.add))

None


#### 81.Write a NumPy program to test whether none of the elements of a given array is zero.

In [ ]:

import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True


#### 82.Write a NumPy program to test whether any of the elements of a given array is non-zero

In [ ]:
import numpy as np
x = np.array([1, 0, 0, 0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))
x = np.array([0, 0, 0, 0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))

Original array:
[1 0 0 0]
Test whether any of the elements of a given array is non-zero:
True
Original array:
[0 0 0 0]
Test whether any of the elements of a given array is non-zero:
False


#### 83.Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number)

In [ ]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a))

Original array
[ 1.  0. nan inf]
Test a given array element-wise for finiteness :
[ True  True False False]


#### 84.Write a NumPy program to test element-wise for positive or negative infinity

In [ ]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for positive or negative infinity:")
print(np.isinf(a))

Original array
[ 1.  0. nan inf]
Test element-wise for positive or negative infinity:
[False False False  True]


#### 85.Write a NumPy program to test element-wise for NaN of a given array.

In [ ]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for NaN:")
print(np.isnan(a))

Original array
[ 1.  0. nan inf]
Test element-wise for NaN:
[False False  True False]


#### 86.Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.


In [ ]:
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


#### 87.Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array

In [ ]:
import numpy as np
X = np.array([1, 7, 13, 105])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[  1   7  13 105]
Size of the memory occupied by the said array:
32 bytes


#### 88.Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. ... 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. ... 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. ... 5. 5. 5.]


#### 89.Write a NumPy program to create an array of the integers from 30 to70

In [ ]:
import numpy as np
array=np.arange(30,71)
print("Array of the integers from 30 to70")
print(array)

Array of the integers from 30 to70
[30 31 32 ... 68 69 70]


#### 90.Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [ ]:
import numpy as np
rand_num = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

15 random numbers from a standard normal distribution:
[-0.867 -0.679 -0.095 ...  1.491 -0.936  1.176]


#### 91.Write a NumPy program to create a 3X4 array using and iterate over it.

In [ ]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

#### 92.Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [ ]:
import numpy as np
v = np.linspace(10, 49, 5)
print("Length 10 with values evenly distributed between 5 and 50:")
print(v)

Length 10 with values evenly distributed between 5 and 50:
[10.   19.75 29.5  39.25 49.  ]


#### 93. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15. 

In [ ]:
import numpy as np
x = np.arange(21)
print("Original vector:")
print(x)
print("After changing the sign of the numbers in the range from 9 to 15:")
x[(x >= 9) & (x <= 15)] *= -1
print(x)

Original vector:
[ 0  1  2 ... 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[ 0  1  2 ... 18 19 20]


#### 94.Write a NumPy program to multiply the values ​​of two given vectors.

In [ ]:
import numpy as np
x = np.array([1, 8, 3, 5])
print("Vector-1")
print(x)
y= np.random.randint(0, 11, 4)
print("Vector-2")
print(y)
result = x * y
print("Multiply the values of two said vectors:")
print(result)

Vector-1
[1 8 3 5]
Vector-2
[6 2 1 8]
Multiply the values of two said vectors:
[ 6 16  3 40]


##### 95.Write a NumPy program to find the number of rows and columns of a given matrix.

In [ ]:
import numpy as np
m= np.arange(10,22).reshape((3, 4))
print("Original matrix:")
print(m)
print("Number of rows and columns of the said matrix:")
print(m.shape)

Original matrix:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Number of rows and columns of the said matrix:
(3, 4)


#### 96.Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [ ]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 97.Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [ ]:
import numpy as np
x = np.random.random((3, 3, 3))
print(x)

[[[0.766 0.777 0.028]
  [0.174 0.154 0.077]
  [0.89  0.75  0.693]]

 [[0.512 0.464 0.568]
  [0.303 0.497 0.683]
  [0.917 0.109 0.495]]

 [[0.233 0.437 0.752]
  [0.481 0.798 0.283]
  [0.433 0.01  0.341]]]


#### 98.Write a NumPy program to create one-dimensional array of single, two and three digit numbers.

In [ ]:
import numpy as np  
nums = np.arange(1, 21)
print("One-dimensional array of single digit numbers:") 
print(nums)
nums = np.arange(10, 21)
print("\nOne-dimensional array of two digit numbers:") 
print(nums)
nums = np.arange(100, 201)
print("\nOne-dimensional array of three digit numbers:") 
print(nums)

One-dimensional array of single digit numbers:
[ 1  2  3 ... 18 19 20]

One-dimensional array of two digit numbers:
[10 11 12 ... 18 19 20]

One-dimensional array of three digit numbers:
[100 101 102 ... 198 199 200]


#### 99.Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows. 

In [ ]:
import numpy as np 
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last rows of the said array:")
new_nums = nums[::-1]
print(new_nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


#### 100.Write a NumPy program to multiply two given arrays of same size element-by-element.

In [ ]:
import numpy as np 
nums1 = np.array([[2, 5, 2],
              [1, 5, 5]])
nums2 = np.array([[5, 3, 4],
              [3, 2, 5]])
print("Array1:") 
print(nums1)
print("Array2:") 
print(nums2)
print("\nMultiply said arrays of same size element-by-element:")
print(np.multiply(nums1, nums2))

Array1:
[[2 5 2]
 [1 5 5]]
Array2:
[[5 3 4]
 [3 2 5]]

Multiply said arrays of same size element-by-element:
[[10 15  8]
 [ 3 10 25]]


# Numpy Practice Questions Set 2

#### 1. Import NumPy as np

In [ ]:
import numpy as np

####2. Create an array of 10 zeros 

In [ ]:
np.zeros(10)

array([0., 0., 0., ..., 0., 0., 0.])

####3. Create an array of 10 ones

In [ ]:
np.ones(10)

array([1., 1., 1., ..., 1., 1., 1.])

####4. Create an array of 10 fives

In [ ]:
np.ones(10) * 5

array([5., 5., 5., ..., 5., 5., 5.])

####5. Create an array of the integers from 10 to 50

In [ ]:
np.arange(10,51)

array([10, 11, 12, ..., 48, 49, 50])

####6. Create an array of all the even integers from 10 to 50

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, ..., 46, 48, 50])

####7. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

####8. Create a 3x3 identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

####9. Use NumPy to generate a random number between 0 and 1

In [ ]:
np.random.rand(1)

array([0.689])

####10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
np.random.randn(25)

array([-0.393,  0.625, -1.705, ..., -0.085,  0.123,  0.975])

####11. Create the following matrix:

In [ ]:
np.arange(1,101).reshape(10,10) / 100

array([[0.01, 0.02, 0.03, ..., 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, ..., 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, ..., 0.28, 0.29, 0.3 ],
       ...,
       [0.71, 0.72, 0.73, ..., 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, ..., 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, ..., 0.98, 0.99, 1.  ]])

####12. Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
np.linspace(0,1,20)

array([0.   , 0.053, 0.105, ..., 0.895, 0.947, 1.   ])

# Numpy Practice Question Set 3

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[3,4]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [ ]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

19. Create a 5x5 integer array from a range between 100 to 300 such that the difference between each element is *8*

In [ ]:
sampleArray = np.arange(100, 300, 8)
sampleArray = sampleArray.reshape(5,5)
print (sampleArray)

[[100 108 116 124 132]
 [140 148 156 164 172]
 [180 188 196 204 212]
 [220 228 236 244 252]
 [260 268 276 284 292]]


20. Following is the provided numPy array. Return array of items by taking the third column from all rows

In [ ]:
sampleArray = np.array([[1,2,3], [4,5,6], [7,8,9]])

print("\n Printing array of items in the third column from all rows")
newArray = sampleArray[...,2]
print(newArray)


 Printing array of items in the third column from all rows
[3 6 9]


21. Split the array into 6 equal-sized sub-arrays

In [ ]:
sampleArray = np.arange(10, 40, 1)
sampleArray = sampleArray.reshape(6,5)
print (sampleArray)

subArrays = np.split(sampleArray, 6) 
print(subArrays)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[array([[10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19]]), array([[20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29]]), array([[30, 31, 32, 33, 34]]), array([[35, 36, 37, 38, 39]])]


22. Print max from axis 0 and min from axis 1 from the following 2-D array.

In [ ]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

minOfAxisOne = np.amin(sampleArray, 1) 
print(minOfAxisOne)

maxOfAxisOne = np.amax(sampleArray, 0) 
print(maxOfAxisOne)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[34 12 53]
[82 94 73]


23. Find element-wise absolute value of a given numpy array.

In [ ]:
array = np.array([-1, -2, 3, -7, 9])
  
print("Given array:\n", array)
array2 = np.absolute(array)
print("Absolute array:\n", array2)

Given array:
 [-1 -2  3 -7  9]
Absolute array:
 [1 2 3 7 9]


24. Find element-wise absolute value of 2d-array.

In [ ]:
array = np.array([[1, -2, 3],
                  [-4, 5, -6]])
  
print("Given array:\n",array)
array1 = np.absolute(array)
  
print("Absolute array:\n",array1)

Given array:
 [[ 1 -2  3]
 [-4  5 -6]]
Absolute array:
 [[1 2 3]
 [4 5 6]]


25. Find element-wise absolute value of 3d-array.

In [ ]:
array = np.array([[[1, -2, 3],[-4, 5, -6]],[[-7.5, -8.22, 9.0],[10.0, 11.5, -12.5]]])
print("Given array:\n",array)
array1 = np.absolute(array)
print("Absolute array:\n",array1)

Given array:
 [[[  1.    -2.     3.  ]
  [ -4.     5.    -6.  ]]

 [[ -7.5   -8.22   9.  ]
  [ 10.    11.5  -12.5 ]]]
Absolute array:
 [[[ 1.    2.    3.  ]
  [ 4.    5.    6.  ]]

 [[ 7.5   8.22  9.  ]
  [10.   11.5  12.5 ]]]


26. Find absolute squareroot of an array.

In [ ]:
arr1 = np.sqrt([1, 4, 9, 16])
arr2 = np.sqrt([6, 10, 18])
print("square-root of an array1  : ", arr1)
print("square-root of an array2  : ", arr2)

square-root of an array1  :  [1. 2. 3. 4.]
square-root of an array2  :  [2.449 3.162 4.243]


27. Round off the values of a given matrix.

In [ ]:
import numpy as np
mat1 = np.matrix('[6.4, 1.3; 12.7, 32.3]')
mat2 = mat1.round()    
print(mat2)

[[ 6.  1.]
 [13. 32.]]


28.  Print max from axis 0 and min from axis 1 from the following 2-D array.

In [ ]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print (sampleArray)
minOfAxisOne = np.amin(sampleArray, 1) 
print("Printing amin Of Axis 1")
print(minOfAxisOne)
maxOfAxisOne = np.amax(sampleArray, 0) 
print("Printing amax Of Axis 0")
print(maxOfAxisOne)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Printing amin Of Axis 1
[34 12 53]
Printing amax Of Axis 0
[82 94 73]


29. Delete the second column from a given array and insert the following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 

newColumn = numpy.array([[10,10,10]])

In [ ]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

print ("Original array\n", sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)


Original array
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


30. Create an array of odd integers from the given array of integers.

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

31. Replace all the numbers greater than 5 with 1 and below 5 with -1 in the array.

In [ ]:
arr = [1,2,6,4,8,9,10]
arr1=[]
for x in arr:
  if x>5:
    arr1.append(1)
  else:
    arr1.append(-1)
arr1

[-1, -1, 1, -1, 1, 1, 1]

32. Append 2 arrays containing numbers from 1 to 10 vertically

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

33. Append 2 arrays containing numbers from 1 to 10  horizontally

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a, b])

array([[0, 1, 2, ..., 1, 1, 1],
       [5, 6, 7, ..., 1, 1, 1]])

34.  Find the number and position of missing values in iris_2d‘s sepallength (1st column)

Load dataset using: 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'


iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [4.7, 3.2, 1.6, 0.2, nan],
       [4.8, 3.1, 1.6, 0.2, nan],
       [4.9, 2.4, 3.3, 1. , nan],
       [4.9, 2.5, 4.5, 1.7, nan]])

35. Select the rows of iris_2d that does not have any nan value.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

36. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]

0.8717541573048718

37. Replace all ccurrences of nan with 0 in numpy array

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 0. , 1.5, 0. ]])

38. Select the rows of iris_2d that does not have any nan value.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

39. Find the unique values and the count of unique values in iris’s 'species' column.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

species = np.array([row.tolist()[4] for row in iris])

np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype='|S15'), array([50, 50, 50]))

40. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:

- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- ‘>=5 –> ‘large’

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

petal_length_cat[:4]

['small', 'small', 'small', 'small']

41. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3

volume = volume[:, np.newaxis]

out = np.hstack([iris_2d, volume])

out[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004]], dtype=object)

42.  Randomly sample iris‘s species such that setose is twice the number of versicolor and virginica

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

species = iris[:, 4]

np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])
print(np.unique(species_out, return_counts=True))

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'), array([77, 37, 36]))


43. What is the value of second longest petallength of species setosa

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')

np.unique(np.sort(petal_len_setosa))[-2]

1.7

44. Sort the iris dataset based on sepallength column.

In [ ]:
print(iris[iris[:,0].argsort()][:20])

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 ...
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


45. Find the most frequent value of petal length (3rd column) in iris dataset.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

b'1.5'


46. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50])

47. From the array a, replace all values greater than 30 to 30 and less than 10 to 10. 

**Input:**

np.random.seed(100)


a = np.random.uniform(1,50, 20)

In [ ]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.clip(a, a_min=10, a_max=30)

array([27.627, 14.64 , 21.801, ..., 10.   , 30.   , 14.43 ])

48. Get the positions of top 5 maximum values in a given array a

In [ ]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a.argsort())

[ 4 13  5 ...  3 10 15]


49. Compute the counts of unique values row-wise. **Input:**

np.random.seed(100)

arr = np.random.randint(1,11,size=(6, 10))

In [ ]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]

    # Counts of all values row wise
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])
print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

[ 1  2  3 ...  8  9 10]


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

50. Convert array_of_arrays into a flat linear 1d array. Input:

**Input:**

arr1 = np.arange(3)

arr2 = np.arange(3,7)

arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])

In [ ]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)


[0 1 2 ... 7 8 9]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """


51. Compute the one-hot encodings (dummy binary variables for each unique value in the array) **Input:**

np.random.seed(101) 

arr = np.random.randint(1,4, size=6)

In [ ]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
(arr[:, None] == np.unique(arr)).view(np.int8)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=int8)

52.  Create row numbers grouped by a categorical variable. Use the following sample from iris species as input. 
**Input:**

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)

species_small = np.sort(np.random.choice(species, size=20))

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))

print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5]


56. Compute the maximum for each row in the given array. 
**Input:**

np.random.seed(100)

a = np.random.randint(1,10, [5,3])

In [ ]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
np.amax(a, axis=1)

array([9, 8, 6, 3, 9])

57. Compute the min-by-max for each row for given 2d numpy array.

**Input:**

np.random.seed(100)

a = np.random.randint(1,10, [5,3])

In [ ]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

array([0.444, 0.125, 0.5  , 1.   , 0.111])

58. Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False

Input:

np.random.seed(100)

a = np.random.randint(0, 5, 10)

In [ ]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
out = np.full(a.shape[0], True)
unique_positions = np.unique(a, return_index=True)[1]
out[unique_positions] = False
print(out)

[False  True False ...  True  True  True]


59. Find the mean of a numeric column grouped by a categorical column in a 2D numpy array.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

numeric_column = iris[:, 1].astype('float')  
grouping_column = iris[:, 4] 

[[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]

output = []
for group_val in np.unique(grouping_column):
    output.append([group_val, numeric_column[grouping_column==group_val].mean()])

output

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

60. Import the image from the following URL and convert it to a numpy array. URL = ‘https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg’

In [ ]:
from io import BytesIO
from PIL import Image
import PIL, requests

URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

I = Image.open(BytesIO(response.content))

arr = np.asarray(I)
arr

array([[[  9,  72, 125],
        [  9,  72, 125],
        [  9,  72, 125],
        ...,
        [ 42, 103, 147],
        [ 42, 103, 147],
        [ 43, 104, 148]],

       [[  9,  72, 125],
        [  9,  72, 125],
        [ 10,  73, 126],
        ...,
        [ 42, 103, 147],
        [ 42, 103, 147],
        [ 43, 104, 148]],

       [[  9,  72, 125],
        [ 10,  73, 126],
        [ 10,  73, 126],
        ...,
        [ 44, 105, 150],
        [ 45, 106, 151],
        [ 45, 106, 151]],

       ...,

       [[ 21,  41,  50],
        [ 29,  51,  64],
        [ 28,  54,  69],
        ...,
        [ 27,  58,  79],
        [ 22,  53,  74],
        [ 19,  47,  69]],

       [[ 27,  51,  63],
        [ 29,  55,  68],
        [ 27,  56,  72],
        ...,
        [ 33,  70,  97],
        [ 27,  64,  91],
        [ 22,  57,  85]],

       [[ 18,  45,  56],
        [ 20,  48,  62],
        [ 21,  52,  70],
        ...,
        [ 15,  51,  77],
        [ 12,  48,  74],
        [ 11,  45,  72]]

61. Drop all nan values from a 1D numpy array 

Input: 

np.array([1,2,3,np.nan,5,6,7,np.nan]) 

Desired Output:

array([ 1.,  2.,  3.,  5.,  6.,  7.])

In [ ]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

62. Compute the euclidean distance between two arrays a and b.

a = np.array([1,2,3,4,5])

b = np.array([4,5,6,7,8])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

dist = np.linalg.norm(a-b)
dist

6.708203932499369

63. Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides. 

Input: 

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

In [ ]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

array([2, 5])

64. Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.

a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])

b_1d = np.array([1,1,1]

In [ ]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

print(a_2d - b_1d[:,None])

[[2 2 2]
 [2 2 2]
 [2 2 2]]


65. Find the index of 5th repetition of number 1 in x.

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [ ]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

[i for i, v in enumerate(x) if v == 1][n-1]

np.where(x == 1)[0][n-1]

8

66. Convert numpy’s datetime64 object to datetime’s datetime object

In [ ]:
dt64 = np.datetime64('2018-02-25 22:10:10')

from datetime import datetime
dt64.tolist()

dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

67. Compute the moving average of window size 3, for the given 1D array. 

Input:

np.random.seed(100)

Z = np.random.randint(10, size=10)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

np.random.seed(100)
Z = np.random.randint(10, size=10)
print('array: ', Z)

moving_average(Z, n=3).round(2)

array:  [8 8 3 ... 2 5 2]


array([6.33, 6.  , 5.67, ..., 2.  , 3.67, 3.  ])

68. Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers.

In [ ]:
length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

seq(start, length, step)

array([ 5,  8, 11, ..., 26, 29, 32])

69. Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, by filling in the missing dates. 

**Input:**

dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)

In [ ]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)

filled_in = np.array([np.arange(date, (date+d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1)

output = np.hstack([filled_in, dates[-1]])
output

out = []
for date, d in zip(dates, np.diff(dates)):
    out.append(np.arange(date, (date+d)))

filled_in = np.array(out).reshape(-1)

output = np.hstack([filled_in, dates[-1]])
output

['2018-02-01' '2018-02-03' '2018-02-05' ... '2018-02-19' '2018-02-21'
 '2018-02-23']


array(['2018-02-01', '2018-02-02', '2018-02-03', ..., '2018-02-21',
       '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

70. From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..] 

Input:

arr = np.arange(15) 

arr

In [ ]:
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

print(gen_strides(np.arange(15), stride_len=2, window_len=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]


71. Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])
b = 2*a 
print(b)

[[ 2  4  6]
 [ 8 10 12]]


72. Convert all the elements of a numpy array from float to integer datatype

In [ ]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])
o = a.astype('int')
print(o)

[[2 3 1]
 [4 2 1]]


73. Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array

In [ ]:
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]])
o = a.astype('bool')
print(o)

[[ True False False]
 [ True  True  True]
 [False False False]]


74. Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

In [ ]:
list_of_numbers = [x for x in range(0, 101, 2)]
o = np.array(list_of_numbers)
print(o)

[  0   2   4 ...  96  98 100]


75. From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match.

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([1,3,2,4,5,7,6,8])
print(np.where(a == b))

(array([0, 3, 4, 7]),)


76. Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])
o = a@b
print(o)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


77. Output the transpose of a matrix (as numpy array)

In [ ]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a_transpose = a.T
print(a_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


78. Output the array element indexes such that the array elements appear in the ascending order

In [ ]:
array = np.array([10,1,5,2])
indexes = np.argsort(array)
print(indexes)

[1 3 2 0]


79. Make an array immutable (read-only) 

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False

80. Create a structured array representing a position (x,y) and a color (r,g,b)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ... ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


81. Subtract the mean of each row of a matrix.

In [ ]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.247 -0.004  0.413 ... -0.451 -0.15   0.493]
 [-0.319 -0.367 -0.134 ... -0.147  0.123 -0.267]
 [ 0.124  0.238 -0.267 ... -0.004  0.034 -0.378]
 [ 0.251  0.026 -0.144 ...  0.338 -0.45   0.3  ]
 [ 0.455 -0.306 -0.37  ... -0.273  0.52   0.414]]


82. Sort an array by the nth column

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[4 5 7]
 [6 6 2]
 [4 2 7]]
[[4 2 7]
 [4 5 7]
 [6 6 2]]


83. Find if a given 2D array has null columns

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


84. Find the nearest value from a given value in an array

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5030544894489398


85. Print all the values of an array.

In [ ]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

86. Create random vector of size 10 and replace the maximum value by 0.

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.    0.387 0.462 0.579 0.114 0.368 0.361 0.88  0.275 0.225]
